### ISSUE TITLE
error docc2html : Could not process document at: /path/to/file.json unsupportedInlineContentType("strong")

### ISSUE THREAD

**Issue by edudnyk** [DoccZz/DocCArchive#2]
Inline content type "strong" is unsupported. It appears for me in the DocC output of Xcode 13 for text in markdown prefixed and suffixed with two wildcards (`**Strong Text**`)

**Comment by helje5** [comment]
Presumably fixed via https://github.com/DoccZz/DocCArchive/pull/4
