### ISSUE TITLE
Images don't have a size anymore

### ISSUE THREAD

**Issue by fruitcoder** [DoccZz/DocCArchive#5]
Building the documentation with Xcode 13.2.1 the images don't have a `size` anymore so the decoding fails with the following message:

`Could not process document at: .../SlothCreator.doccarchive/data/tutorials/slothcreator.json keyNotFound(CodingKeys(stringValue: "size", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "references", intValue: nil), _JSONKey(stringValue: "slothcreator-intro.png", intValue: nil), CodingKeys(stringValue: "variants", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"size\", intValue: nil) (\"size\").", underlyingError: nil))`

**Comment by helje5** [comment]
Fixed in https://github.com/DoccZz/DocCArchive/releases/tag/0.2.12
